### ISSUE TITLE
Help me.Can rust CUDA 0.3 be deployed in windows? How can I encounter the situation that rust CUDA 0.3 cannot be compiled? The CPU / add demo fails to compile

### ISSUE THREAD

**Issue by zofoc** [Rust-GPU/Rust-CUDA#82]
Can rust CUDA 0.3 be deployed in windows? How can I encounter the situation that rust CUDA 0.3 cannot be compiled? The CPU / add demo fails to compile

**Comment by zofoc** [comment]
error: failed to run custom build command for `rustc_codegen_nvvm v0.3.0 (E:\Work\RustCUDA\Rust-CUDA-0.3\crates\rustc_codegen_nvvm)`

Caused by:
  process didn't exit successfully: `E:\Work\RustCUDA\Rust-CUDA-0.3\target\debug\build\rustc_codegen_nvvm-5af0b793bf34f027\build-script-build` (exit code: 101)
  --- stderr
  llvm-config: error: LLVM-7.1.dll is missing
  thread 'main' panicked at 'command did not execute successfully: "E:\\Work\\RustCUDA\\rustc_codegen_nvvm-llvm-windows-x86_64\\windows-x86_64\\bin\\llvm-config.exe" "--link-shared" "--libs" "bitreader" "bitwriter" "ipo" "lto" "nvptx"
  expected success, got: exit code: 1', crates\rustc_codegen_nvvm\build.rs:217:16
  stack backtrace:
     0:     0x7ff7ed5244cf - std::backtrace_rs::backtrace::dbghelp::trace
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
     1:     0x7ff7ed5244cf - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff7ed5244cf - std::sys_common::backtrace::_print_fmt
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\sys_common\backtrace.rs:67
     3:     0x7ff7ed5244cf - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\sys_common\backtrace.rs:46
     4:     0x7ff7ed53cfda - core::fmt::write
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\core\src\fmt\mod.rs:1149
     5:     0x7ff7ed51cbe8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\io\mod.rs:1697
     6:     0x7ff7ed526e16 - std::sys_common::backtrace::_print
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\sys_common\backtrace.rs:49
     7:     0x7ff7ed526e16 - std::sys_common::backtrace::print
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\sys_common\backtrace.rs:36
     8:     0x7ff7ed526e16 - std::panicking::default_hook::closure$1
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:211
     9:     0x7ff7ed5268fc - std::panicking::default_hook
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:228
    10:     0x7ff7ed527475 - std::panicking::rust_panic_with_hook
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:606
    11:     0x7ff7ed52705b - std::panicking::begin_panic_handler::closure$0
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:502
    12:     0x7ff7ed524df7 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\sys_common\backtrace.rs:139
    13:     0x7ff7ed526fb9 - std::panicking::begin_panic_handler
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:498
    14:     0x7ff7ed5e4660 - core::panicking::panic_fmt
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\core\src\panicking.rs:107
    15:     0x7ff7ed4518f4 - build_script_build::output
                                 at E:\Work\RustCUDA\Rust-CUDA-0.3\crates\rustc_codegen_nvvm\build.rs:42
    16:     0x7ff7ed4536bf - build_script_build::rustc_llvm_build
                                 at E:\Work\RustCUDA\Rust-CUDA-0.3\crates\rustc_codegen_nvvm\build.rs:217
    17:     0x7ff7ed451609 - build_script_build::main
                                 at E:\Work\RustCUDA\Rust-CUDA-0.3\crates\rustc_codegen_nvvm\build.rs:19
    18:     0x7ff7ed45a696 - core::ops::function::FnOnce::call_once
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\library\core\src\ops\function.rs:227
    19:     0x7ff7ed45a696 - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\library\std\src\sys_common\backtrace.rs:123
    20:     0x7ff7ed45b50c - std::rt::lang_start::closure$0<tuple$<> >
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\library\std\src\rt.rs:145
    21:     0x7ff7ed523e17 - core::ops::function::impls::impl$2::call_once
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\library\core\src\ops\function.rs:259
    22:     0x7ff7ed523e17 - std::panicking::try::do_call
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:406
    23:     0x7ff7ed523e17 - std::panicking::try
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:370
    24:     0x7ff7ed523e17 - std::panic::catch_unwind
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panic.rs:133
    25:     0x7ff7ed523e17 - std::rt::lang_start_internal::closure$2
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\rt.rs:128
    26:     0x7ff7ed523e17 - std::panicking::try::do_call
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:406
    27:     0x7ff7ed523e17 - std::panicking::try
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panicking.rs:370
    28:     0x7ff7ed523e17 - std::panic::catch_unwind
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\panic.rs:133
    29:     0x7ff7ed523e17 - std::rt::lang_start_internal
                                 at /rustc/532d2b14c05f9bc20b2d27cbb5f4550d28343a36\/library\std\src\rt.rs:128
    30:     0x7ff7ed456e57 - main
    31:     0x7ff7ed5e2a3c - invoke_main
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    32:     0x7ff7ed5e2a3c - __scrt_common_main_seh
                                 at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    33:     0x7ffe775e7034 - BaseThreadInitThunk
    34:     0x7ffe787a2651 - RtlUserThreadStart

E:\Work\RustCUDA\Rust-CUDA-0.3\examples\cuda\cpu\add>

**Comment by zofoc** [comment]
I downloaded the official pre build version of the library. It seems that there is no llvm-7.1.dll. Do I need to pull llvm-7.1 full source and full Compiler?

**Comment by LegNeato** [comment]
This is working these days.
